name: Build

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - run: |
          mkdir staging
          cp web/target/web*.war staging/web.war
          cp api/target/api*.war staging/api.war
          cp inventory/target/inventory*.war staging/inventory.war
          cd staging
          sha256sum *.war > hashes.txt
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging